version: "3.4"

# Development environment override
services:
  php:
    build:
      context: ./core
      target: salt_core_dev
      args:
        - BUILD_NUMBER=${BUILD_NUMBER:-x}
        - BUILD_DATE=${BUILD_DATE:-0}
        - COMMIT=${COMMIT:-unknown}
        - VERSION=${VERSION:-3.0.0-dev}
    #environment:
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # See https://github.com/docker/for-linux/issues/264
      # The `remote_host` below may optionally be replaced with `remote_connect_back`
      # XDEBUG_MODE required for step debugging
      #XDEBUG_MODE: debug
      # default port for Xdebug 3 is 9003
      # idekey=VSCODE if you are debugging with VSCode
      #XDEBUG_CONFIG: >-
      #  client_host=host.docker.internal
      #  idekey=PHPSTORM
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      #PHP_IDE_CONFIG: serverName=api-platform
    volumes:
      - ./core:/srv/core:rw
      - ./core/docker/php/conf.d/opcache.ini.dev:/usr/local/etc/php/conf.d/opcache.ini
      - ./core/var:/srv/core/var:rw

#  pwa:
#    build:
#      context: ./pwa
#      target: salt_core_pwa_dev
#    volumes:
#      - ./pwa:/usr/src/pwa:rw,cached 

  web:
    volumes:
      - ./core/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./core/public:/srv/core/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

