imports:
    - { resource: parameters.yml }
    - { resource: pdo-options.php }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CftfBundle/Resources/config/services.yml" }
    - { resource: "@SaltUserBundle/Resources/config/services.yml" }
    - { resource: "@GithubFilesBundle/Resources/config/services.yml" }
    - { resource: "@SaltSiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    database_host: '%env(MYSQL_HOST)%'
    database_port: '%env(MYSQL_PORT)%'
    database_name: '%env(MYSQL_DATABASE)%'
    database_user: '%env(MYSQL_USER)%'
    database_password: '%env(MYSQL_PASSWORD)%'
    secret: '%env(SECRET)%'
    cookie_secret: '%env(COOKIE_SECRET)%'
    local_uri_host: '%env(LOCAL_URI_HOST)%'
    github_client_id: '%env(GITHUB_CLIENT_ID)%'
    github_client_secret: '%env(GITHUB_CLIENT_SECRET)%'
    brand_logo_url: '%env(BRAND_LOGO_URL)%'
    brand_logo_style: '%env(BRAND_LOGO_STYLE)%'
    brand_link_url: '%env(BRAND_LINK_URL)%'
    brand_link_style: '%env(BRAND_LINK_STYLE)%'
    comments_feature: '%env(COMMENTS_FEATURE)%'
    firebase_api_key: '%env(FIREBASE_API_KEY)%'
    firebase_db_url: '%env(FIREBASE_DB_URL)%'
    firebase_auth_domain: '%env(FIREBASE_AUTH_DOMAIN)%'
    firebase_project_id: '%env(FIREBASE_PROJECT_ID)%'
    firebase_client_id: '%env(FIREBASE_CLIENT_ID)%'
    firebase_client_email: '%env(FIREBASE_CLIENT_EMAIL)%'
    firebase_private_key: '%env(FIREBASE_PRIVATE_KEY)%'
    firebase_prefix: '%env(FIREBASE_PREFIX)%'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
        #handler_id:  nelmio_security.session.handler
        #save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: session
        cookie_lifetime: 0
        #cookie_secure: true
        cookie_httponly: true
        gc_maxlifetime: 3600
        gc_probability: 25
        gc_divisor:     100
        metadata_update_threshold: 120
    fragments:       ~
    http_method_override: true
    request:
      formats:
        jsonapi: 'application/vnd.api+json'
        csv: ['text/csv', 'text/plain']
    #translator: { fallbacks: ['%locale%'] }
    assets:
        version: '170482'
        packages:
          encore:
            json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
    globals:
      github_client_id: "%github_client_id%"
      brand_logo_url: "%brand_logo_url%"
      brand_logo_style: "%brand_logo_style%"
      brand_link_url: "%brand_link_url%"
      brand_link_style: "%brand_link_style%"
      firebase_api_key: "%firebase_api_key%"
      firebase_auth_domain: "%firebase_auth_domain%"
      firebase_db_url: "%firebase_db_url%"
      firebase_project_id: "%firebase_project_id%"
      firebase_prefix: "%firebase_prefix%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

stof_doctrine_extensions:
    default_locale: en_US

#    # Only used if you activated the Uploadable extension
#    uploadable:
#        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
#        default_file_path:       %kernel.root_dir%/../web/uploads
#
#        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
#        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
#
#        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
#        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            tree: true
            timestampable: true

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                options:  "%pdo_options%"
                charset:  utf8mb4
                schema_filter: ~^(?!(auth_session|cache_items|LearningStandards|std_*|grade_level))~
                server_version: 5.7
                mapping_types:
                    json: string
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            json: App\Doctrine\Types\JsonType
            datetime: App\Doctrine\Types\DateTimeType
        #mapping_types:
        #    json: string
        #    uuid: char(36)
        #    uuid_binary: binary(16)

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                second_level_cache:
                    enabled: false
                    log_enabled: true
                mappings:
                    app:
                        type: annotation
                        prefix: App\Entity
                        dir: "%kernel.root_dir%/../src/App/Entity"
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"

jms_di_extra:
    locations:
        all_bundles: true
        #bundles: []
        directories: ["%kernel.root_dir%/../src"]

jms_serializer:
    handlers:
        datetime:
            default_format: "c" #ISO8601
            default_timezone: "UTC"

csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        json:
            config:
                timeout: 2.0
                headers:
                    Accept: 'application/json'

nelmio_security:
#    signed_cookie:
#        names: ['*']
#        secret: '%cookie_secret%'
#        hash_algo: sha256
    #cookie_session:
    #    enabled: true
    #    name: session
    #    secure: true
    #encrypted_cookie:
    #    names: ['*']
    #    secret: '%cookie_secret%'
    #    algorithm: rijndael-256
    forced_ssl:
        enabled: false

    clickjacking:
        paths:
            '^/cftree/doc/': ALLOW
            '^/.*': DENY
        content_types: []
    external_redirects:
        whitelist:
            - google.com
            
    # Forces Microsoft/Chrome XSS-Protection with its block mode.
    xss_protection:
        enabled: true
        mode_block: true

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/ims/case/v1p0/':
            forced_allow_origin_value: '*'
            allow_origin: ['*']
            allow_headers:
                - 'Accept-Encoding'
                - 'If-Modified-Since'
                #- 'If-None-Match'
                - 'Content-Type'
                - 'Content-Range'
                - 'Content-Disposition'
                - 'Content-Description'
                - 'X-Requested-With'
                #- '*'
            allow_methods: ['GET']
            expose_headers:
                - 'X-Total-Count'
                - 'X-OpenSALT'
                #- '*'
            max_age: 60

al_swagger_ui:
    static_resources:
        resource_dir: "app/Resources/swagger-docs/"
        resource_list_filename: api-docs.json
    resource_list: al_swagger_ui_static_resource_list

qandidate_toggle:
    persistence: config
    toggles:
        comments:
            name: comments
            status: '%comments_feature%'

simple_things_entity_audit:
    #entity_manager: default
    table_prefix: 'audit_'
    table_suffix: ''
    #revision_field_name: rev
    #revision_type_field_name: revtype
    revision_table_name: audit_revision
    #revision_id_field_type: integer
    audited_entities:
        - CftfBundle\Entity\LsDoc
        - CftfBundle\Entity\LsDocAttribute
        - CftfBundle\Entity\LsDocSubject
        - CftfBundle\Entity\LsItem
        - CftfBundle\Entity\LsItemConcept
        - CftfBundle\Entity\LsAssociation
        - CftfBundle\Entity\LsDefAssociationGrouping
        - CftfBundle\Entity\LsDefItemType
        - CftfBundle\Entity\LsDefConcept
        - CftfBundle\Entity\LsDefGrade
        - CftfBundle\Entity\LsDefLicence
        - CftfBundle\Entity\LsDefSubject
        - CftfBundle\Entity\CfRubric
        - CftfBundle\Entity\CfRubricCriterion
        - CftfBundle\Entity\CfRubricCriterionLevel
        - Salt\UserBundle\Entity\Organization
        - Salt\UserBundle\Entity\User
        - Salt\UserBundle\Entity\UserDocAcl
        - App\Entity\ChangeEntry
    global_ignore_columns:
        - password
