version: '2.1'
services:
  app:
    image: opensalt/app:${COMMIT}

  phpfpm:
    image: opensalt/php:7.1-fpm
    depends_on:
      - db
    environment:
      SYMFONY__MYSQL__DATABASE: "${MYSQL_DATABASE}"
      SYMFONY__MYSQL__USER: "${MYSQL_USER}"
      SYMFONY__MYSQL__PASSWORD: "${MYSQL_PASSWORD}"
      SYMFONY__MYSQL__HOST: "${MYSQL_HOST:-db}"
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      DB_USE_RDS_CERT:
      BRAND_LOGO_URL:
      BRAND_LINK_URL:
    volumes_from:
      - app
    working_dir: /var/www/html

  nginx:
    image: opensalt/nginx:1.11-alpine
    depends_on:
      - phpfpm
    environment:
      UPSTREAM_HOST: phpfpm:9000
    volumes_from:
      - app
    working_dir: /var/www/html

  db:
    image: percona:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
