version: '2.1'
services:
  app:
    image: opensalt/app:${COMMIT}

  phpfpm:
    image: opensalt/php:7.3-fpm
    depends_on:
      - db
    environment:
      #XDEBUG_CONFIG: remote_host=Your_IP_Address
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
      APP_SECRET:
      COOKIE_SECRET:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      BRAND_LOGO_URL:
      BRAND_LOGO_STYLE:
      BRAND_LINK_URL:
      BRAND_LINK_STYLE:
      FOOTER_LEFT_TEXT:
      ALLOW_LOCAL_DEV: "true"
      ALLOW_EXTERNAL_DEV_IPS:
      DEV_COOKIE:
      FIREBASE_API_KEY:
      FIREBASE_AUTH_DOMAIN:
      FIREBASE_DB_URL:
      FIREBASE_PROJECT_ID:
      FIREBASE_CLIENT_ID:
      FIREBASE_CLIENT_EMAIL:
      FIREBASE_PRIVATE_KEY:
      FIREBASE_PREFIX:
      MAILER_TRANSPORT:
      MAILER_HOST:
      MAILER_USER:
      MAILER_PASSWORD:
      MAILER_AUTH_MODE:
      MAILER_PORT:
      COMMENTS_FEATURE:
      COMMENT_ATTACHMENTS:
      CREATE_ACCOUNT_FEATURE:
      USE_MAIL_FEATURE:
      MAIL_FEATURE_FROM_EMAIL:
      GOOGLE_CAPTCHA_SITE_KEY:
      GOOGLE_CAPTCHA_SECRET_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_S3_PREFIX:
      AWS_S3_BUCKET:
      AWS_S3_REGION:
      ATTACHMENT_URL_PREFIX:
      BUCKET_PROVIDER:
      LOCAL_FILESYSTEM_PATH:
      CASE_NETWORK_CLIENT_ID:
      CASE_NETWORK_CLIENT_SECRET:
      CASE_NETWORK_TOKEN_ENDPOINT:
      CASE_NETWORK_SCOPE:
    volumes_from:
      - app
    working_dir: /var/www/html

  nginx:
    image: opensalt/nginx:1.16-alpine
    depends_on:
      - phpfpm
    environment:
      UPSTREAM_HOST: phpfpm:9000
    volumes_from:
      - app
    working_dir: /var/www/html

  db:
    image: percona:${MYSQL_VERSION}
    volumes:
      - "${PROJ_DIR:-..}/docker/mysql/max_allowed_packet.cnf:/etc/mysql/conf.d/max_allowed_packet.cnf:ro"
      - "${PROJ_DIR:-..}/docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf:ro"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
