version: '2.1'
services:
  phpfpm:
    #build:
    #  context: ./php/fpm
    image: opensalt/php:7.1-fpm
    #image: opensalt/php:7.1-fpm-xdebug
    depends_on:
      - db
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      #XDEBUG_CONFIG: remote_host=Your_IP_Address
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      DB_USE_RDS_CERT:
      BRAND_LOGO_URL:
      BRAND_LOGO_STYLE:
      BRAND_LINK_URL:
      BRAND_LINK_STYLE:
      ALLOW_LOCAL_DEV: "true"
      ALLOW_EXTERNAL_DEV_IPS:
      DEV_COOKIE:
      COMMENTS_FEATURE:
      FIREBASE_API_KEY:
      FIREBASE_AUTH_DOMAIN:
      FIREBASE_DB_URL:
      FIREBASE_PROJECT_ID:
      FIREBASE_CLIENT_ID:
      FIREBASE_CLIENT_EMAIL:
      FIREBASE_PRIVATE_KEY:
      FIREBASE_PREFIX:
    volumes:
      - &project_root "${PROJ_DIR:-..}:/var/www/html"
    working_dir: /var/www/html

  nginx:
    #build:
    #  context: ./nginx
    image: opensalt/nginx:1.13-alpine
    depends_on:
      - phpfpm
    environment:
      UPSTREAM_HOST: phpfpm:9000
    ports:
      - "${PORT:-3000}:80"
    volumes:
      - *project_root
    working_dir: /var/www/html
    networks:
      default:
      external:
        aliases:
          - "${COMPOSE_PROJECT_NAME}-salt"

  db:
    image: percona:${MYSQL_VERSION}
    volumes:
      - "${PROJ_DIR:-..}/docker/data/mysql:/var/lib/mysql"
      - "${PROJ_DIR:-..}/docker/mysql/max_allowed_packet.cnf:/etc/mysql/conf.d/max_allowed_packet.cnf:ro"
      - "${PROJ_DIR:-..}/docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf:ro"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

  #neo4j:
  #elasticsearch:

#volumes:
#  mysql-data: {}

networks:
  external:
