version: '2.1'
services:
  # Tools used
  # the docker-compose format does not have a way to specify not to run these upon "up"
  # so we set to command to /bin/true to exit right away
  phpcli:
    #build:
    #  context: ./php
    image: opensalt/php:7.1-cli
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
      COMMENTS_FEATURE:
      FIREBASE_API_KEY:
      FIREBASE_AUTH_DOMAIN:
      FIREBASE_DB_URL:
      FIREBASE_PROJECT_ID:
      FIREBASE_CLIENT_ID:
      FIREBASE_CLIENT_EMAIL:
      FIREBASE_PRIVATE_KEY:
      FIREBASE_PREFIX:
    volumes:
      - &project_root "${PROJ_DIR:-..}:/var/www/html"
    working_dir: /var/www/html
    command: [ /bin/true ]

  composer:
    #build:
    #  context: ./composer
    image: opensalt/composer:1.4-7.1
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
    volumes:
      - *project_root
      - "${PROJ_DIR:-..}/docker/data/composer/slash:/composer"
      - "${PROJ_DIR:-..}/docker/data/composer/root-user:/root/composer"
      - "${PROJ_DIR:-..}/docker/data/composer/passwd.tmp:/etc/passwd"
    working_dir: /var/www/html
    command: [ "-q" ]

  gulp:
    #build:
    #  context: ./gulp
    image: opensalt/gulp:latest
    volumes:
      - "${PROJ_DIR:-..}:/build/app"

#volumes:
