version: '2.1'
services:
  # Tools used
  # the docker-compose format does not have a way to specify not to run these upon "up"
  # so we set to command to /bin/true to exit right away
  phpcli:
    #build:
    #  context: ./php
    image: opensalt/php:7.3-fpm
    environment:
      #XDEBUG_CONFIG: remote_host=Your_IP_Address
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
      APP_SECRET:
      COOKIE_SECRET:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      BRAND_LOGO_URL:
      BRAND_LOGO_STYLE:
      BRAND_LINK_URL:
      BRAND_LINK_STYLE:
      FOOTER_LEFT_TEXT:
      ALLOW_LOCAL_DEV: "true"
      ALLOW_EXTERNAL_DEV_IPS:
      DEV_COOKIE:
      FIREBASE_API_KEY:
      FIREBASE_AUTH_DOMAIN:
      FIREBASE_DB_URL:
      FIREBASE_PROJECT_ID:
      FIREBASE_CLIENT_ID:
      FIREBASE_CLIENT_EMAIL:
      FIREBASE_PRIVATE_KEY:
      FIREBASE_PREFIX:
      MAILER_TRANSPORT:
      MAILER_HOST:
      MAILER_USER:
      MAILER_PASSWORD:
      MAILER_AUTH_MODE:
      MAILER_PORT:
      COMMENTS_FEATURE:
      COMMENT_ATTACHMENTS:
      CREATE_ACCOUNT_FEATURE:
      USE_MAIL_FEATURE:
      MAIL_FEATURE_FROM_EMAIL:
      GOOGLE_CAPTCHA_SITE_KEY:
      GOOGLE_CAPTCHA_SECRET_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_S3_BUCKET:
      AWS_S3_REGION:
      AWS_S3_PREFIX:
      ATTACHMENT_URL_PREFIX:
      BUCKET_PROVIDER:
      LOCAL_FILESYSTEM_PATH:
      CASE_NETWORK_CLIENT_ID:
      CASE_NETWORK_CLIENT_SECRET:
      CASE_NETWORK_TOKEN_ENDPOINT:
      CASE_NETWORK_SCOPE:

      MAILTRAP_INBOX_ID:
      MAILTRAP_API_KEY:
    volumes:
      - &project_root "${PROJ_DIR:-..}:/var/www/html"
    working_dir: /var/www/html
    command: [ /bin/true ]

  composer:
    #build:
    #  context: ./composer
    image: opensalt/php:7.3-fpm
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
    volumes:
      - *project_root
      - "${PROJ_DIR:-..}/docker/data/composer/slash:/composer"
      - "${PROJ_DIR:-..}/docker/data/composer/root-user:/root/composer"
      - "${PROJ_DIR:-..}/docker/data/composer/passwd.tmp:/etc/passwd"
    working_dir: /var/www/html
    entrypoint: [ "composer", "--ansi" ]
    command: [ "-q" ]

  gulp:
    #build:
    #  context: ./gulp
    image: opensalt/gulp:latest
    volumes:
      - "${PROJ_DIR:-..}:/build/app"

#volumes:
