# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        json:
            config:
                timeout: 2.0
                headers:
                    Accept: 'application/json'
#        default: null
#        my_client:
#            config:
#                base_uri: 'http://example.com'
