nelmio_cors:
    defaults:
        #allow_credentials: false
        #origin_regex: true
        #allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-OpenSALT']
        expose_headers: ['Link']
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
    paths:
        '^/ims/case/v1p0/':
            forced_allow_origin_value: '*'
            allow_origin: ['*']
            allow_headers:
                - 'Accept-Encoding'
                - 'If-Modified-Since'
                #- 'If-None-Match'
                - 'Content-Type'
                - 'Content-Range'
                - 'Content-Disposition'
                - 'Content-Description'
                - 'X-Requested-With'
                - 'X-OpenSALT'
                #- '*'
            allow_methods: ['GET']
            expose_headers:
                - 'X-Total-Count'
                - 'X-OpenSALT'
                #- '*'
            max_age: 60
        '^/': null
