# see https://github.com/qandidate-labs/qandidate-toggle-bundle/blob/master/README.md#configuration

qandidate_toggle:
    persistence: config
    toggles:
        comments:
            name: comments
            status: '%comments_feature%'
        comment_attachments:
            name: comment_attachments
            status: '%comment_attachments%'
        create_account:
            name: create_account
            status: '%create_account_feature%'
        email_feature:
            name: email_feature
            status: '%use_mail_feature%'

