twig:
    #default_path: '%kernel.project_dir%/templates'
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Set to null for Symfony 4.4 to use framework.error_controller instead
    exception_controller: ~
    #number_format:
    #    thousands_separator: ','
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'form/fields.html.twig'
    globals:
      github_client_id: "%github_client_id%"
      brand_logo_url: "%brand_logo_url%"
      brand_logo_style: "%brand_logo_style%"
      brand_link_url: "%brand_link_url%"
      brand_link_style: "%brand_link_style%"
      google_captcha_site_key: "%google_captcha_site_key%"
      footer_left_text: "%footer_left_text%"
      base_template: '%base_template%'


