name: Static Analysis

on: 
  pull_request: ~

defaults:
  run:
    shell: bash

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: "json,xsl,dom"
          ini-values: "memory_limit=-1"
          coverage: none

      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Install Psalm
        run: |
          cd $GITHUB_WORKSPACE/core/tools/psalm
          composer install --no-progress --ansi
          ./vendor/bin/psalm --version

      - name: Generate Psalm baseline
        run: |
          cd $GITHUB_WORKSPACE/core
          git checkout -m ${{ github.base_ref }}
          composer install --no-progress --ansi
          ./tools/psalm/vendor/bin/psalm --set-baseline=../.github/psalm/psalm.baseline.xml --no-progress

      - name: Psalm
        run: |
          cd $GITHUB_WORKSPACE/core
          git checkout -m FETCH_HEAD
          composer install --no-progress --ansi
          ./tools/psalm/vendor/bin/psalm --output-format=github --no-progress

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: "json,xsl,dom"
          ini-values: "memory_limit=-1"
          coverage: none

      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Install PHPStan
        run: |
          cd $GITHUB_WORKSPACE/core/tools/phpstan
          composer install --no-progress --ansi

      - name: Generate PHPStan baseline
        run: |
          cd $GITHUB_WORKSPACE/core
          git checkout -m ${{ github.base_ref }}
          composer install --no-progress --ansi
          touch phpstan-baseline.neon
          ./tools/phpstan/vendor/bin/phpstan --generate-baseline --no-progress --ansi

      - name: PHPStan on PR
        run: |
          cd $GITHUB_WORKSPACE/core
          git checkout -m FETCH_HEAD
          composer install --no-progress --ansi
          ./tools/phpstan/vendor/bin/phpstan --error-format=github --no-progress --ansi
